### ISSUE TITLE
[Feature Request] Support setups with PV inverter only, no SMA Home Manager?

### ISSUE THREAD

**Issue by StijnDC** [wimleers/homebridge-sma-home-manager#15]
Hi Wim,

I've been looking for a replacement for the old SMA plugin and this seems to really fit the bill.
Currently however I Don't have a Sunny manager.
Would it be possible to enable just providing the readouts of the inverter using this plugin when no energy manager is detected?
I Would love to be able to read the data properly instead of interpreting lux values.

Thanks!

**Comment by wimleers** [comment]
While theoretically possible, this would massively increase the complexity of this codebase.

This plugin specifically reads as _little as possible_ from the PV inverter, and as much as possible from the SMA Home Manager.

Why? Because the inverter's data can only be read through Modbus. Which is known to be brittle and slow. If you read too often, it's known to crash. Every piece of data you want requires reading a separate Modbus register. It _works_, but is not a good fit for showing realtime data.

In stark contrast: the SMA Home Manager 2.0's data: it is _broadcast_ once per second on the network. Perfect.

So if I were to add support for _only_ PV inverters, then I'd have to

1. read _far more_ Modbus registers and ignore half of the data that the SMA Home Manager 2.0 is broadcasting 🤪
2. or maintain two different codebases, of which I only use one

**Conclusion: I'm afraid I can't do this. It's more of a support burden than I'm willing to bear.**

I suggest:
- continuing to use https://github.com/codyc1515/homebridge-sma-inverter, it still works fine and it will continue to do so
- start your own fork, and feel free to start from the last commit before https://github.com/wimleers/homebridge-sma-home-manager/commit/87bbe7d4299fa364c3a63218fcd5bc77b8940e13, in which I already did a bunch of clean-up to https://github.com/codyc1515/homebridge-sma-inverter

Good luck!
